### ISSUE TITLE
Output message bug found when using --make-ref flag to create LD reference

### ISSUE THREAD

**Issue by xinyu-c9** [eldronzhou/SDPR#11]
Dear Author,

When I was trying to run SDPR to make my own LD reference, I found an output message bug shown below.

![image](https://github.com/eldronzhou/SDPR/assets/116093647/b6c4f6cf-97af-4e33-86d5-2b54650ab7fc)

When running SDPR on chrom1, The first line and The second line from the bottom showed correct chromosome information, but the snp counts in between showed in the wrong line.

This may be a bug to fix, which may confuse users.

Your attention to these recommendations would be greatly appreciated.

Best,
Xingyu

**Comment by eldronzhou** [comment]
Dear Xingyu,

Thank you for bring this issue up to me. I have fixed it in the latest commit.

Best,
Geyu
