### ISSUE TITLE
add the  functional annotation

### ISSUE THREAD

**Issue by zyx125186** [eldronzhou/SDPR#12]
Dear author,

Hello! I hope this email finds you well. I have a question for you about accurately defining the r2 in an LD threshold. Additionally, at the end of your recent article, you mentioned that including functional annotations can increase accuracy. I would like to know if you have done any recent work in this area. If so, I would love to discuss how to include functional annotations in more detail.

Thank you for your time and consideration.

Best regards,

**Comment by eldronzhou** [comment]
Hi zyx,

The r2 is basically the maximum LD allowed between SNPs in two LD blocks. You can leave it as the default when running SDPR. Some other work to define approximately independent LD block can be found [here](https://academic.oup.com/bioinformatics/article/38/1/255/6321454). I haven't done any extension to include annotation for SDPR. The way to add annotation is to assume that the prior likelihood of assignment is related to the function annotation, similar to [SBayesRC](https://www.biorxiv.org/content/10.1101/2022.10.12.510418v1) or [GWEB](https://www.researchgate.net/publication/374207242_Estimating_genetic_architecture_and_integrating_functional_annotations_improve_polygenic_risk_scores_derived_from_GWAS_summary_statistics).  Hope this helps.

**Comment by zyx125186** [comment]
Dear Zhou,
Thank you for your advice. I do animal genetics and want to apply some models of PGS to animals. I wonder if you know the application of PGS in animals?
Best wishes!!!



---- Replied Message ----
| From | Geyu ***@***.***> |
| Date | 04/08/2024 21:32 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [eldronzhou/SDPR] add the functional annotation (Issue #12) |

Hi zyx,

The r2 is basically the maximum LD allowed between SNPs in two LD blocks. You can leave it as the default when running SDPR. Some other work to define approximately independent LD block can be found here. I haven't done any extension to include annotation for SDPR. The way to add annotation is to assume that the prior likelihood of assignment is related to the function annotation, similar to SBayesRC or GWEB. Hope this help.

**Comment by eldronzhou** [comment]
Method like SDPR is designed for large scale GWAS summary statistics as input. I don't think this is the setting for animal genetics as the sample size is usually smaller and individual level genotype data is available. You may want to try BSLMM or other Bayesian method with individual level data as the input to compute PGS in animals.

**Comment by zyx125186** [comment]
Thanks to your suggestion, I tried to convert the individual-level data into gwas summary statistics and calculate Pearson correlation coefficients, but the results don't seem to be as good as the traditional GBLUP,I think it may be that the data is small（I used 770k chip data, and there were only more than 1000 phenotypic individuals）, and at the same time there is a bias between the converted data from individual level data to gwas summary statistics.
Thank you again for your advice.
Best wishes



---- Replied Message ----
| From | Geyu ***@***.***> |
| Date | 04/09/2024 03:22 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [eldronzhou/SDPR] add the functional annotation (Issue #12) |

Method like SDPR is designed for large scale GWAS summary statistics as input. I don't think this is the setting for animal genetics as the sample size is usually smaller and individual level genotype data is available. You may want to try BSLMM or other Bayesian method with individual level data as the input to compute PGS in animals.
