### ISSUE TITLE
Issues about the running time

### ISSUE THREAD

**Issue by MJ-bioinfo** [eldronzhou/SDPR#13]
I read the Manual file and it mentions "When running in parallel using (22*3 = 66 threads), SDPR is able to finish MCMC in around 15 minutes". However when I ran the SDPR in my linux centos7 environment, it usually costs more than 2 hours or more per chromosome in 5 threads and 40GB memory. In many cases it stopped exporting any results while the program still kept running.

I have used my own data as the reference, which contains 2202526 SNPs on chromosome 1 as an example. So I was wondering if it is a memory issue? What is a suitable memory setting in SDPR? Or something else may go wrong? Is SDPR not suitable for my linux system?

I have no idea how to improve the situation totally, and I would be grateful if someone could give any suggestions or ideas about this issue. Thanks in advance!

**Comment by eldronzhou** [comment]
Hello, 

Thanks for using SDPR. In the manual, it is stated that SDPR is able to finish MCMC in around 15 minutes for ~0.8 million Hapmap 3 SNPs across all chromosomes. I noticed that you have more than 2 million SNPs on chromosome 1 so it would take considerably longer time and memory to run SDPR. Is there any reason not use Hapmap3 SNPs as it is currently a standard practice?

**Comment by MJ-bioinfo** [comment]
Thanks for your reponse! 
I tried larger memory setting following your answer and it seemed to work. I used my own data for some methdological reasons so I didn't used Hapmap3 data, but thanks a lot!
