### ISSUE TITLE
0 common SNP between reference ,validation and summary

### ISSUE THREAD

**Issue by ooozcl** [eldronzhou/SDPR#9]
hello，
  when my summary file is SNP,A1,A2,BETA,P，the following error will be reported：terminate called after throwing an instance of 'std::out_of_range' what(): stod。when my summary file is SNP,A1,A2,Z，show 0 common SNP between reference ,validation and summary，Is this because there are no common SNPs in my files?or some other reason?

**Comment by eldronzhou** [comment]
Hi,

Thank you for using SDPR. Is your summary file publicly available or could you send it to me (geyu.zhou@yale.edu) so that I can investigate the issue?

**Comment by ooozcl** [comment]
Sorry to bother you, it’s  my problem, the summary file format SNP, A1, A2, Z can run.
